ZLIB = ../testz/zlib
UNZLIB = ../testz/unzip


EE_OBJS  += $(ZLIB)/adler32.o $(ZLIB)/compress.o  $(ZLIB)/crc32.o  $(ZLIB)/gzio.o $(ZLIB)/uncompr.o $(ZLIB)/infcodes.o  $(ZLIB)/trees.o $(ZLIB)/deflate.o $(ZLIB)/inflate.o $(ZLIB)/infblock.o $(ZLIB)/inftrees.o $(ZLIB)/infutil.o $(ZLIB)/inffast.o $(ZLIB)/zutil.o  aio-fio.o $(UNZLIB)/explode.o $(UNZLIB)/unreduce.o $(UNZLIB)/unshrink.o $(UNZLIB)/unzip.o   

